package reporter

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eljakani/ward/internal/models"
)

// MarkdownReporter generates a Markdown report.
type MarkdownReporter struct {
	OutputDir string
}

func NewMarkdownReporter(outputDir string) *MarkdownReporter {
	if outputDir == "" {
		outputDir = "."
	}
	return &MarkdownReporter{OutputDir: outputDir}
}

func (r *MarkdownReporter) Name() string   { return "markdown" }
func (r *MarkdownReporter) Format() string { return "md" }

func (r *MarkdownReporter) Generate(_ context.Context, report *models.ScanReport) error {
	counts := report.CountBySeverity()

	var sb strings.Builder

	// Title
	sb.WriteString("# Ward Security Report\n\n")
	sb.WriteString(fmt.Sprintf("**Project:** %s  \n", report.ProjectContext.ProjectName))
	sb.WriteString(fmt.Sprintf("**Laravel:** %s  \n", report.ProjectContext.LaravelVersion))
	sb.WriteString(fmt.Sprintf("**PHP:** %s  \n", report.ProjectContext.PHPVersion))
	sb.WriteString(fmt.Sprintf("**Duration:** %s  \n", report.Duration.Round(1e6)))
	sb.WriteString(fmt.Sprintf("**Scanners:** %s  \n\n", strings.Join(report.ScannersRun, ", ")))

	// Summary table
	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("| Total | %d |\n", len(report.Findings)))
	sb.WriteString("|-------|---|\n")
	for _, sev := range []models.Severity{models.SeverityCritical, models.SeverityHigh, models.SeverityMedium, models.SeverityLow, models.SeverityInfo} {
		if c := counts[sev]; c > 0 {
			sb.WriteString(fmt.Sprintf("| %s %s | %d |\n", severityEmoji(sev), sev.String(), c))
		}
	}
	sb.WriteString("\n")

	// Findings grouped by severity
	sb.WriteString("## Findings\n\n")
	for _, sev := range []models.Severity{models.SeverityCritical, models.SeverityHigh, models.SeverityMedium, models.SeverityLow, models.SeverityInfo} {
		sevFindings := filterFindings(report.Findings, sev)
		if len(sevFindings) == 0 {
			continue
		}

		sb.WriteString(fmt.Sprintf("### %s %s (%d)\n\n", severityEmoji(sev), sev.String(), len(sevFindings)))

		for _, f := range sevFindings {
			sb.WriteString(fmt.Sprintf("#### %s — %s\n\n", f.ID, f.Title))
			sb.WriteString(fmt.Sprintf("- **File:** `%s:%d`\n", f.File, f.Line))
			sb.WriteString(fmt.Sprintf("- **Category:** %s\n", f.Category))
			sb.WriteString(fmt.Sprintf("- **Scanner:** %s\n\n", f.Scanner))
			sb.WriteString(f.Description + "\n\n")

			if f.CodeSnippet != "" {
				sb.WriteString("```\n")
				sb.WriteString(f.CodeSnippet + "\n")
				sb.WriteString("```\n\n")
			}

			if f.Remediation != "" {
				sb.WriteString("**Remediation:**\n\n")
				sb.WriteString(f.Remediation + "\n\n")
			}

			if len(f.References) > 0 {
				sb.WriteString("**References:**\n")
				for _, ref := range f.References {
					sb.WriteString(fmt.Sprintf("- %s\n", ref))
				}
				sb.WriteString("\n")
			}

			sb.WriteString("---\n\n")
		}
	}

	sb.WriteString("*Generated by [Ward](https://github.com/Eljakani/ward) v0.1.0*\n")

	outPath := filepath.Join(r.OutputDir, "ward-report.md")
	if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing Markdown report to %s: %w", outPath, err)
	}

	return nil
}

func severityEmoji(s models.Severity) string {
	switch s {
	case models.SeverityCritical:
		return "\xF0\x9F\x94\xB4" // red circle
	case models.SeverityHigh:
		return "\xF0\x9F\x9F\xA0" // orange circle
	case models.SeverityMedium:
		return "\xF0\x9F\x9F\xA1" // yellow circle
	case models.SeverityLow:
		return "\xF0\x9F\x9F\xA2" // green circle
	default:
		return "\xF0\x9F\x94\xB5" // blue circle
	}
}

func filterFindings(findings []models.Finding, sev models.Severity) []models.Finding {
	var result []models.Finding
	for _, f := range findings {
		if f.Severity == sev {
			result = append(result, f)
		}
	}
	return result
}
